const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{
  fs.mkdirSync('tmp',{recursive:true});
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1400,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765');
  await page.locator('.nav[data-view="library"]').click();
  const filing=page.locator('#documents .card').filter({hasText:'Hyundai Motor India Limited'});
  await filing.getByRole('button',{name:'Inspect coverage'}).click();
  await page.getByRole('button',{name:'Inspect layout on page 36',exact:true}).click();
  await page.locator('#source-content h3').filter({hasText:'Native layout'}).waitFor();
  const tables=await page.locator('#source-content .native-table table').count();
  if(tables!==4)throw Error('Expected four preserved Hyundai table fragments.');
  await page.locator('#source-dialog').screenshot({path:'tmp/stage11-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#source-dialog').screenshot({path:'tmp/stage11-mobile.png'});
  const overflow=await page.locator('#source-dialog').evaluate(e=>e.scrollWidth>e.clientWidth);
  const href=await page.getByRole('link',{name:'Export page layout'}).getAttribute('href');
  const exported=await (await page.request.get('http://127.0.0.1:8765'+href)).json();
  if(exported.inventory.tables.length!==4)throw Error('Full page export lost table fragments');
  await page.getByRole('button',{name:'Back to page coverage'}).click();
  await page.getByRole('button',{name:'Inspect layout on page 36',exact:true}).waitFor();
  const summary={desktop:true,mobile:true,fullTableCandidates:tables,export:true,backNavigation:true,dialogOverflow:overflow,errors};
  fs.writeFileSync('evals/results/browser-stage11.json',JSON.stringify(summary,null,2));
  console.log(JSON.stringify(summary));await browser.close();
  if(overflow||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
